name: Deploy SQL Changes

on:
  push:
    branches:
      - main
    paths:
      - 'database/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detect changed Table files
        id: changed-tables
        uses: tj-actions/changed-files@v44
        with:
          files: database/Tables/**/*.sql

      - name: Deploy changed Table scripts
        if: steps.changed-tables.outputs.any_changed == 'true'
        shell: cmd
        run: |
          for %%f in (${{ steps.changed-tables.outputs.all_changed_files }}) do (
            sqlcmd -S localhost\SQLEXPRESS -d Test_Store_Procedure -i "%%f" -E -C
          )

      - name: Detect changed Stored Procedure files
        id: changed-sps
        uses: tj-actions/changed-files@v44
        with:
          files: database/StoredProcedures/**/*.sql

      - name: Deploy changed Stored Procedure scripts
        if: steps.changed-sps.outputs.any_changed == 'true'
        shell: cmd
        run: |
          for %%f in (${{ steps.changed-sps.outputs.all_changed_files }}) do (
            sqlcmd -S localhost\SQLEXPRESS -d Test_Store_Procedure -i "%%f" -E -C
          )
